### ISSUE TITLE
Anchoring on trucks non-obvious or malformed in some cases

### ISSUE THREAD

**Issue by AaronSofaer** [DevProgress/more-tacos#100]
Request from a user:

> Is there a way to improve the location of the resulting truck? I'm trying to get them on specific corners, and they go down and to the left.

**Comment by mschempp** [comment]
Before and after of resulting truck. You have to zoom in quite a bit to avoid clipping other landmarks.
![before](https://cloud.githubusercontent.com/assets/22200113/18520736/b71d1126-7a6e-11e6-80f3-47d326fcefbc.PNG)
![after](https://cloud.githubusercontent.com/assets/22200113/18520737/b999a004-7a6e-11e6-891c-59fb9fadadbb.PNG)

**Comment by kielni** [comment]
This was caused by the change for https://github.com/DevProgress/more-tacos/issues/91
The x is where the center of the truck will go on click, so it needs to match the center of the truck. I can remove the x or change it: http://stackoverflow.com/questions/21371062/how-to-change-the-cross-below-the-marker-google-map-v3. What do you think @silasmeredith ?

**Comment by silasmeredith** [comment]
I do like having some indicator or where the truck will be placed. The 'X' was fulfilling that purpose, but maybe only for someone like me who knew it was there and knew what it did. Is there some other way of making it clear which exact place the truck is going to, such as a little arrow? If not, then I don't see any way around have the center be the center.

You guys know more about this than I do, so if you feel strongly that the center should be the center, we should go with that.

**Comment by kielni** [comment]
Yes, I think the x makes sense when it's the point of a map pin, but confusing for the truck shape.  https://github.com/DevProgress/more-tacos/commit/983cb58f1f80814e49d26cf017910a17996453db removes the x on drag and uses the default (center) anchor point so the truck will stay where you place it.
