### ISSUE TITLE
No scrolling

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#103]
From @JaneRuby 
1. I think it shouldn't scroll in web view, it should all fit in the screen without a scroll
1. To fix that, I think the text at the bottom should be reorganized and not stacked as it is

Built by DevProgress | Design by Jane Ruby using Truck by John Caserta and Taco by Focus Lab, from the Noun Project | Want to help? It's open source!

^possible solution using pipes and keeping the text at the bottom on one line

**Comment by kielni** [comment]
There's just not very much room on mobile; the title and description takes up almost half of the height.  What do you think about putting the description in a dismissible popover?  It could close on click and/or automatically after some amount of time (10s?)

![screen shot 2016-09-15 at 12 03 50 pm](https://cloud.githubusercontent.com/assets/1649528/18563453/86e7c81a-7b3c-11e6-9769-4d2ece47b285.png)

**Comment by JaneRuby** [comment]
Yes I agree!

**Comment by JaneRuby** [comment]
Can you also adjust the text at the bottom? I think there is an open issue for that 😊

**Comment by silasmeredith** [comment]
Makes sense to me. Again, you guys are the experts on this, so I'll follow your lead.

**Comment by kielni** [comment]
see https://github.com/DevProgress/more-tacos/pull/105 for version with text adjustments

![screen shot 2016-09-15 at 12 52 30 pm](https://cloud.githubusercontent.com/assets/1649528/18566031/1bcd3852-7b47-11e6-843c-8c5a49618f29.png)

**Comment by silasmeredith** [comment]
Looks good to me!

**Comment by kielni** [comment]
fixed by https://github.com/DevProgress/more-tacos/pull/105
