### ISSUE TITLE
custom clustered markers

### ISSUE THREAD

**Issue by kielni** [DevProgress/more-tacos#14]
need a truck-shaped cluster icon: truck shape with transparent center

how big does it need to be? where do the numbers go exactly?

**Comment by kielni** [comment]
like this but with trucks
<img width="811" alt="screen shot 2016-09-08 at 5 16 33 pm" src="https://cloud.githubusercontent.com/assets/1649528/18371301/0b342be0-75e8-11e6-9133-15d3a44bff3f.png">
: https://googlemaps.github.io/js-marker-clusterer/examples/advanced_example.html

**Comment by andrewjtimmons** [comment]
Hi!

This has an open source set of emoji
http://emojione.com/

What if I took this emoji and photoshopped it to say 'Tacos'

http://emojipedia.org/emoji-one/2.0/delivery-truck/

What size are you looking for?

**Comment by kielni** [comment]
@jjandoc is making taco truck icons for the regular markers.  I don't know what size the cluster marker needs to be; big enough to contain the numbers.

**Comment by jjandoc** [comment]
We have control over the font, size, and color of the numbers so you can make the icons whatever sizes and fit the text accordingly. Bigger numbers will need bigger images. If there's a LOT of pins, I'm not sure if there's a way to switch over to writing shorter notation like "10.5K". There's probably a host of other performance problems that come in once there's that many.

**Comment by jjandoc** [comment]
Image should be a png with alpha transparency. The default plugin images range from 53x52 to 90x89, but there's complete flexibility in defining these images.

**Comment by jjandoc** [comment]
I can implement custom images for this if there's any in particular people would like to use.

**Comment by kielni** [comment]
I think this is good for now.
