### ISSUE TITLE
Link with lattitude/longitude not working

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#16]
e.g. the link below was from a taco truck smack dab in the middle of Columbus Circle by Central Park in Manhattan, but the link takes you out into the Atlantic.

https://devprogress.us/more-tacos/#40.76806919965931_-73.98184980237733

**Comment by jillh510** [comment]
c22d557

**Comment by silasmeredith** [comment]
@jillh510 , I might be missing something here, but when I follow the link about on my Chromebook, it asks for my current location and zooms the map to my current location, rather than to the Columbus Circle location that it should go to. Do I need to clear cache, or perhaps there's another open ticket about this? Thanks.

**Comment by silasmeredith** [comment]
Awesome, works like a charm now!
