### ISSUE TITLE
Click/tap truck to save, instead of a separate "save" button

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#19]

**Comment by nathanaelphilip** [comment]
not really sure how feasible this is since you have to click a marker to drag it. I think the only option would be to save each time a marker is moved, and remove any previous locations from this session.

i would like another dev’s opinion on this, but I don’t think it’s feasible.

**Comment by jillh510** [comment]
We could track the mousedown and mouseup times, and if they're below some hysteresis, assume it was a click rather than a drag.

**Comment by jjandoc** [comment]
How about moving the "save" button to an info window that appears on dragend of the marker.

**Comment by silasmeredith** [comment]
@jjandoc , I like the idea of having the save button near the truck itself. It's way less confusing for the user. Here's an idea that might be the easiest to develop, and the easiest to use:
- Once the truck is dragged, the popup changes from "Drag the taco truck, then click Save" to the "Save" button itself.
- After the first save, the button disappears until the truck is dragged again, then reappears. 
- The instructions "Drag the taco truck, then click Save" never appear again.
- Remove the option to close the popup.

Thoughts?

**Comment by jjandoc** [comment]
Sounds perfect. I can take a crack at this this morning.

**Comment by silasmeredith** [comment]
Thank you, Jon!

**Comment by jjandoc** [comment]
Pull request #48 submitted.
