### ISSUE TITLE
Change title to "TacoTruck.Party"

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#20]

**Comment by nathanaelphilip** [comment]
Is this just the `<title>` Tag, or the `<h1>` tag, or both?

**Comment by silasmeredith** [comment]
![2016-09-09_14-10-50](https://cloud.githubusercontent.com/assets/22085972/18397681/496d2236-7697-11e6-99d3-0b79d6d80b12.jpg)

I don't know HTML, but I was thinking the big title at the top. Shown in attached image.

**Comment by kielni** [comment]
https://github.com/DevProgress/more-tacos/pull/29
