### ISSUE TITLE
Shareable text on screen after saving truck

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#23]
Print prominently on the screen right when user saves truck:

“Tell your friend: ‘Hey! I just put a (virtual) taco truck on the map for you. Hopefully, when the taco truck invasion happens, they’ll put a real taco truck there! LINK.’ ”

**Comment by silasmeredith** [comment]
Whoops, looks like this functionality was added, but the text should match the text in the description of this issue. I failed to specify this, but the LINK should be the www.tacotrucks/party link that contains lattitude and longitude of the most recent truck

**Comment by nathanaelphilip** [comment]
sure thing. do you mean `tacotrucks.party/#lat_lng` ?

**Comment by silasmeredith** [comment]
@nathanaelphilip , I believe that's right. I don't know what the exact URL convention will be, but yes, I'm refering to the link that sends you to the correct latitude and longitude. Thank you!

**Comment by silasmeredith** [comment]
Sorry for the delay. Just getting up to speed on GitHub and notifications.Any newbie advice welcome!

**Comment by silasmeredith** [comment]
@nathanaelphilip , it's best I think to put this in the popup, with the Donate, Facebook, and Twitter buttons.

**Comment by silasmeredith** [comment]
@nathanaelphilip , I might be missing something, but I think we're still in the same spot we were before: the text is there, but the link is not. We either need to print the link, or hyperlink the whole thing with the lat/lon link.

**Comment by nathanaelphilip** [comment]
@silasmeredith http://quick.as/j2GQim44B Is that not what you’re talking about?

**Comment by silasmeredith** [comment]
After saving, the text should read:

“Tell your friend: ‘Hey! I just put a (virtual) taco truck on the map for you. Hopefully, when the taco truck invasion happens, they’ll put a real taco truck there! https://devprogress.us/more-tacos/#40.72122548672435_-73.95179580356906_18’ ”

**Comment by kielni** [comment]
Earlier, I changed the text to "I just sponsored a virtual taco truck. You can, too. Taco trucks on every corner." for consistency with the rest of the text.  I find "invasion" a little over the top maybe, and we don't use that anywhere else.  What do you think?

**Comment by silasmeredith** [comment]
Agreed, no "invasion."

This conversation is happening several places, so let's move this to the slack channel for now.

**Comment by silasmeredith** [comment]
After Slack discussion:

"Tell your friends: "Hey, check out my new (virtual) taco truck!"

**Comment by kielni** [comment]
looks fixed to me
