### ISSUE TITLE
Add text at bottom attributing image source (icon from Creative Commons)

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#25]

**Comment by silasmeredith** [comment]
Note to self: once icons are finalized, write attribution text, then assign to @kielni

**Comment by kielni** [comment]
@silasmeredith we can add this whenever you write the text/find the link; the icon source won't change
you can leave it unassigned with help wanted tag for anyone to claim

**Comment by silasmeredith** [comment]
Let's use this:

“Taco truck icon build by Jane Ruby out of some awesome icons:  ICONNAME(LINK) by Focus Lab and ICONNAME(LINK) by John Caserta, from the Noun Project"

@JaneRuby , can you send the Icon Name, as well as the link, to each of the 2 icons? Many thanks!

**Comment by silasmeredith** [comment]
Whoops, we forgot ", from the Noun Project." Whole text: "Taco truck icon build by Jane Ruby using
Truck by John Caserta and Taco by Focus Lab, from the Noun Project."

Also: is there a reason we put the open source link at the bottom? I thought we didn't want people outside of DevProgress involved in building this.

Thanks!

**Comment by kielni** [comment]
if they're not in the DevProgress github org, it works like this:
- click Fork on top right (this gets them their own copy of the code)
- do stuff with local copy
- push changes to user's version
- open PR against this repo
- someone in DevProgress reviews change and accepts/rejects/requests changes

I think we do want to invite anyone to take a look and contribute; we can choose what to accept/revise/reject as needed.

**Comment by kielni** [comment]
fixed by https://github.com/DevProgress/more-tacos/commit/7b49a16ab3664d

**Comment by silasmeredith** [comment]
@kielni , that makes sense. Thanks for explaining!
