### ISSUE TITLE
Facebook and Twitter sharing need to link to specific Latitude and Longitude

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#45]
People want to share their taco truck, not just the platform in general.

**Comment by silasmeredith** [comment]
Not sure why this one was closed; maybe there was a branch that hasn't gotten merged yet. But the Facebook link still goes to the generic link, not the lat/lon link: https://devprogress.us/more-tacos/

**Comment by jillh510** [comment]
Looks like anything past the hashmark is stripped by FB: http://stackoverflow.com/questions/29600877/facebook-share-url-having-hash

**Comment by kielni** [comment]
@nathanaelphilip, looks like we've reached the point where we need that routing lib; can you drop it in?

**Comment by kielni** [comment]
need real URLs for https://github.com/DevProgress/more-tacos/issues/82

**Comment by silasmeredith** [comment]
This actually seems to be working right in Facebook: I was able to post (to "Only Me" of course) and follow the link, and it worked. 

Only Twitter seems to be going to the default location (D.C.) instead of the specific lat/long link. Are other people seeing the same thing? (Careful if you post to Facebook! Always post to "Only Me" for now!)

**Comment by kielni** [comment]
Both Twitter links (top right and after save) look good to me.

<img width="843" alt="screen shot 2016-09-12 at 8 31 34 pm" src="https://cloud.githubusercontent.com/assets/1649528/18460643/0cdd1e46-7928-11e6-92f9-02c15195d9e8.png">

If it's not working for you, can you paste in a screenshot of the Twitter popup?

**Comment by silasmeredith** [comment]
Alright, it's working for me now!

Any reason not to close this ticket?

**Comment by kielni** [comment]
nope!
