### ISSUE TITLE
share buttons

### ISSUE THREAD

**Issue by kielni** [DevProgress/more-tacos#5]
We need share buttons:

Facebook https://developers.facebook.com/docs/plugins/share-button#configurator
- with preview metadata

Twitter https://dev.twitter.com/web/tweet-button 
- sample Tweet: I just sponsored a virtual taco truck. You can, too. Save The  #Tacos.

Pinterest

No final URL yet; use a placeholder for now.

**Comment by nathanaelphilip** [comment]
do we have graphics created for the share images?

**Comment by kielni** [comment]
No, just standard Facebook and Twitter buttons

**Comment by kielni** [comment]
share URL will be http://tacotruck.party

**Comment by nathanaelphilip** [comment]
I meant the graphics that show up on the user’s Facebook timeline or in the Tweet (if we wanted to make it a Twitter Card).

**Comment by kielni** [comment]
fixed by https://github.com/DevProgress/more-tacos/pull/27

**Comment by silasmeredith** [comment]
I could be wrong, but this one doesn't seem to be complete. There aren't any Facebook/Twitter buttons on main page yet.

I'm just learning GitHub, but for some reason I can't see #27. Maybe I have my filters set wrong?

**Comment by nathanaelphilip** [comment]
hi @silasmeredith this shows up after the user shares a truck.

**Comment by nathanaelphilip** [comment]
That’s where the initial “design” had them. If they also need to be in the main HTML, I can add them there as well.

**Comment by kielni** [comment]
I made them always appear on the top right of the map, but am having alignment issues (see https://github.com/DevProgress/more-tacos/issues/40)
