### ISSUE TITLE
"Donate" and "Share" buttons should persist when saved truck is dragged

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#53]
The "Donate" and "Share" buttons are the core of what we're doing here. Currently, they disappear as soon as a saved truck is dragged. Let's keep them in the popup, but add a saved button below them if the truck is dragged.

**Comment by kielni** [comment]
I think they're kinda big to keep in the info window that gets dragged around; they're always available from the top right of the map; is that enough?

<img width="157" alt="screen shot 2016-09-10 at 12 51 37 pm" src="https://cloud.githubusercontent.com/assets/1649528/18413185/693385ec-7755-11e6-954c-53515769b618.png">

**Comment by silasmeredith** [comment]
What if after saving we showed "Donate," "Facebook," "Twitter," and copyable text; and once it's dragged again, we show "Donate," "Facebook," "Twitter," and "Save." That way, we greatly cut down the size of the popup when the user is trying to place it, but still keep "Donate" and share buttons prominent.

**Comment by kielni** [comment]
👍

**Comment by nathanaelphilip** [comment]
this has been fixed in #69

**Comment by silasmeredith** [comment]
Hmmmm, same question as the other resolved tickets from last night: is there a branch out there that hasn't been merged yet? I'm not seeing the functionality on the front-end. Re-posting the goal here:

After clicking "Save," the popup contains buttons for "Donate," "Facebook," "Twitter," and copyable text (including lat/lon link); and once the truck is dragged again, the popup shows "Donate," "Facebook," "Twitter," and "Save." That way, we greatly cut down the size of the popup when the user is trying to place it, but still keep "Donate" and share buttons prominent.

**Comment by kielni** [comment]
<img width="323" alt="screen shot 2016-09-12 at 5 39 33 pm" src="https://cloud.githubusercontent.com/assets/1649528/18457735/ea2c4466-790f-11e6-8483-184defbe65e8.png">

I think it's a little big; what do you think?

**Comment by silasmeredith** [comment]
I like the way it's working now!

The big popup is clunky, it's true, but it wouldn't be that much less clunky without the donate/facebook/twitter buttons. I just really don't want that message (donate and share!) to get lost, and I think few people will use the buttons in the corner of the map.

Is there another way of keeping the Donate and Share! message prominent without the big popup?

**Comment by kielni** [comment]
Not that I want to attempt before launch.  They could go in a custom overlay but that's a pain because we'd have to write code to keep it in sync with the marker.
