### ISSUE TITLE
When dragging Taco Truck, there's an "close" X in the top left...

### ISSUE THREAD

**Issue by AaronSofaer** [DevProgress/more-tacos#55]
... which obviously cannot be interacted with, because the icon is being dragged at the time that it's visible. We shouldn't be rendering the X.

**Comment by nathanaelphilip** [comment]
I don’t see this in Chrome. Is there a specific browser you’ve tested this in? Can you upload a screenshot?

**Comment by nathanaelphilip** [comment]
I see it now. Will remove the X.

**Comment by nathanaelphilip** [comment]
Fixed in PR #69.
