### ISSUE TITLE
Apply new design styles

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#56]
![screen shot 2016-09-10 at 2 51 58 pm](https://cloud.githubusercontent.com/assets/22085972/18412999/915647fc-776a-11e6-99d1-47f8f0e36a4c.png)

**Comment by kielni** [comment]
@mattrothenberg can you add 
- link to how to use the TacoTruck.Party font 
- hex color code for TacoTruck.Party text
- hex color code for background

**Comment by kielni** [comment]
notes from @JaneRuby 

Google font for headline

![Google font for headline](https://cloud.githubusercontent.com/assets/1649528/18423969/36889992-785f-11e6-9354-5618cae550f9.jpg)

#F44336  is standard red, maybe for the title
#1A237E  is a deeper blue, it is from a different blue strain than the button we have, so I think it could work

change the large red text to black and use the dark blue for the slogan.

**Comment by JaneRuby** [comment]
<img width="785" alt="screen shot 2016-09-11 at 9 08 37 pm copy" src="https://cloud.githubusercontent.com/assets/19919252/18443166/a4d3d664-78e1-11e6-848b-42af15dfa6fb.png">

**Comment by JaneRuby** [comment]
<img width="785" alt="mock up" src="https://cloud.githubusercontent.com/assets/19919252/18443195/c674b856-78e1-11e6-81b0-b47691b212eb.png">

**Comment by JaneRuby** [comment]
^new mockup, with additional changes discussed with Kimberly

**Comment by mattrothenberg** [comment]
That looks fine to me @JaneRuby. I think there's a color contrast issue between the grey text and the light background color underneath the map, though. I also don't think that shade of red meshes well with the color scheme.

**Comment by JaneRuby** [comment]
Yeah Matt, I did the mock up really quickly and didn't fix that. Kimberly
knows about it and will adjust it.

**Comment by JaneRuby** [comment]
#D50000
#B71C1C
#C62828

^these are other possible red shades that could work.

**Comment by mattrothenberg** [comment]
Awesome, thanks!

**Comment by JaneRuby** [comment]
![mock up](https://cloud.githubusercontent.com/assets/19919252/18454203/0941dff4-7911-11e6-8e2b-0d28b479781e.png)

another design thought to deal with the awkward space.

**Comment by mattrothenberg** [comment]
FWIW, I actually prefer it underneath the **TacoTruck.Party** logo. Since it's the tagline and all...

**Comment by JaneRuby** [comment]
@mattrothenberg if that's the case (totally fine with it, then something need to happen with the black color text. Regardless I think the content needs to be re-worked, so maybe that will be good incentive?

**Comment by silasmeredith** [comment]
Design live at TacoTruck.Party is looking good! If there's anything you want to change, definitely speak up; we're nearly ready for a DevProgress internal release.

**Comment by JaneRuby** [comment]
@silasmeredith i think the content writing is still throwing me off. Too much repetition. Totally up to you, but possible changes I would do:

Slogan: "Make #TacoTrucksOnEveryCorner a reality."

Text body: "When a Trump supporter warned that unchecked immigration would lead to taco trucks on every corner, we thought that sounded fantastic! Help us make this American dream an American reality -- place a taco truck on the map, and share it with friends!"

**Comment by silasmeredith** [comment]
I like it! I just added quotes around the quote, and removed the word "unchecked" (on the off chance someone takes this to mean that Hillary Clinton supports unchecked immigration). @kielni @jillh510 @nathanaelphilip or others, can we tweak this? After that, are there any other design tweaks, or should we close this ticket?

Slogan: "Make #TacoTrucksOnEveryCorner a reality."

Text body: "When a Trump supporter warned that immigration would lead to 'taco trucks on every corner,' we thought that sounded fantastic! Help us make this American dream an American reality -- place a taco truck on the map, and share it with friends!"

**Comment by jillh510** [comment]
I'm monkeying with text at the moment and can take care of this.

**Comment by JaneRuby** [comment]
Matt had proposed the idea of altering the red tone to fit better. I could go either way on it, but mocked up some other color options (really quickly and roughly), just to put the idea out there to others... 
![d50000](https://cloud.githubusercontent.com/assets/19919252/18461525/807e3e50-7948-11e6-8690-d46223229dad.png)
![ef5350](https://cloud.githubusercontent.com/assets/19919252/18461526/80816c4c-7948-11e6-8ed1-18da3bd1e80e.png)
![e57373](https://cloud.githubusercontent.com/assets/19919252/18461527/8083d220-7948-11e6-8cd2-37cc057f4beb.png)

**Comment by JaneRuby** [comment]
Also I tested it with blue, just in case:
![1976d2](https://cloud.githubusercontent.com/assets/19919252/18461532/90536a62-7948-11e6-8be2-7fe60ff8d054.png)

**Comment by JaneRuby** [comment]
feel free to say yay or nay, just wanted to be thorough

**Comment by silasmeredith** [comment]
I think it looks good as is, but if y'all feel strongly about one of these, speak up, you know a lot more about design than I do!

**Comment by JaneRuby** [comment]
@silasmeredith I would like to see a version with the text edits, and then I can make a "judgement call", if that's what we will call it... lol

**Comment by silasmeredith** [comment]
Okee doke! @JaneRuby can you coordinate with @jillh510 ?

**Comment by JaneRuby** [comment]
yup!
