### ISSUE TITLE
Uncaught TypeError in console for Windows-Chrome

### ISSUE THREAD

**Issue by AaronSofaer** [DevProgress/more-tacos#57]
In Windows Chrome, but not in OSX Chrome, there's the following Type Errors in the console upon loading the page (the first one) and submitting a truck (the second one):

https://www.dropbox.com/s/tog0nw5o0fx7bbm/typeerrors.jpg?dl=0

**Comment by kielni** [comment]
Googling the filename says that's from a browser extension (ie not the Taco Truck page)

https://www.reasoncoresecurity.com/vapi-client.js-23cdb391a53e1d10fb83a37493c93af38180e119.aspx
