### ISSUE TITLE
Tweak initial popup text, so that it makes sense to a user following a lat/lon link

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#58]
The resolution of #16 uncovered a new issue: when a user follows a link they receive to a specific truck, it just says "Drag the taco truck..." I think a little additional text could make a lot more sense for this user, without confusing the user who comes to the site without a lat/lon link:

Replace "Drag the taco truck, then click 'Save' " ...

...with "Your very own (virtual) taco truck! Make a new truck for a friend: drag the truck, then click 'Save' "

**Comment by silasmeredith** [comment]
Spanish text:

Tu propio (virtual) camión de tacos! Haz un nuevo camión para un amigo : arrastra el camión, luego haz clic en "Save"

**Comment by jillh510** [comment]
Fixed with 5fdca04
