### ISSUE TITLE
When following a lat/lon link, it should ask to go to users actual location. It should skip that step, and go to the lat/lon link, because that's the whole point of sharing.

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#64]

**Comment by jillh510** [comment]
Can you provide the URL that went to the user's location rather than the lat/long location? (this behavior can happen if there's a problem with parsing the lat/long)

**Comment by kielni** [comment]
This is fixed; does not attempt geolocation if lat/lng in URL.
