### ISSUE TITLE
The active truck needs to always be in the foreground, in front of existing trucks, and in front of clusters

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#66]

**Comment by nathanaelphilip** [comment]
This is a duplicate of #60

**Comment by silasmeredith** [comment]
Not sure how this is a duplicate of #60 . This may just be because of my own ignorance. FOr now, I'd like to keep this one open, because we need a record of the issue that the USER experiences. If they're linked, we can close them at the same time.

**Comment by kielni** [comment]
Yes, definitely a duplicate.  I'll copy the text from this one over there since this one is more English-y and less code-y.
