### ISSUE TITLE
Clustering not working

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#72]
Here's Columbus Circle from above (near-ish to 1745 Broadway, New York, NY)
![screenshot 2016-09-11 at 1 13 50 pm](https://cloud.githubusercontent.com/assets/22085972/18419149/9e17a2ca-7822-11e6-8373-2ceefd8c6ed2.png)

Here's the same area zoomed in:
![screenshot 2016-09-11 at 1 15 09 pm](https://cloud.githubusercontent.com/assets/22085972/18419150/9e1934c8-7822-11e6-95bc-ddec7a9bbbd4.png)

All the trucks disappeared.

One option: remove clustering entirely for first release, because with a small number of trucks that may look better anyway. Then figure out how to add in clustering, as the number of trucks goes up.

**Comment by kielni** [comment]
fixed by actually checking in the icon: https://github.com/DevProgress/more-tacos/commit/902ba04bf44c65cb8cbf58d8ce4540b55e0594e9
