### ISSUE TITLE
Website no longer asks for current location; always defaults to Washington D.C.

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#79]
As before, it should ask for permission to view current location, and go there if they say yes. 

Caveat: as before, it should NOT ask this if following a lat/lon link. In that case, it should go directly to that lat/lon.

**Comment by kielni** [comment]
This is probably a user settings issue; which browser?  If you click allow location: Never it won't ask you again, and will go to the default location.

**Comment by silasmeredith** [comment]
I experienced this on two devices (Chromebook and Windows laptop), both in Chrome, both after having cleared all cache for all time. So I think it's really a bug.

**Comment by jillh510** [comment]
I also saw this issue in an incognito Chrome window, until I went to Chrome settings->Privacy->Location->Manage Exceptions and explicitly removed the permission I'd given previously for the site.

**Comment by silasmeredith** [comment]
Hmmm, I'm getting this on Chrome, in incognito mode. It's set to "ask" for locations, with no exceptions, and it still defaults to D.C. In fact, I changed it to "allow," and still defaults to D.C.

What are you seeing on your browsers? Does it go to your currently location?

Thanks for following up with this!

**Comment by jillh510** [comment]
I'm seeing a more serious problem in the console: "getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details."

Can we serve via https?

**Comment by rachavez** [comment]
OS X El Cap (10.11.6) running Safari 9.1.3: the website defaults to WDC, but does ask if I would like to use my default location. I say yes, and the map changes, as it should.

**Comment by rachavez** [comment]
Same behavior happens with Firefox (48.0.2) - WDC appears first, but I'm asked to use my location. I agree and map changes. 

However, this does not happen with Chrome (52.0.2743, but updating soon). No request to use default location, but the URL does show my lat/lon. Why it does not autoupdate I don't know.

**Comment by silasmeredith** [comment]
Yeah, it works on Safari on my iPhone, and Chrome on my iPhone. 

So it looks like where we're at is that it mostly works on most browsers, except for Chrome on Windows desktop. Is that accurate? If that's the case, that lowers the priority level on this bug, though it would still be nice to fix.

**Comment by jillh510** [comment]
It's a tough one for sure. Seems that it works properly on Chrome if there's no entry in the Privacy->Locations list for tacotruck.party, and I open a new window (in other words, if I remove the entry in Settings, and then open a new _tab_, I get the wrong behavior) and I use https.

And in other bizarreness, the console warning is gone with https, but appears intermittently when I go to http://tacotruck.party.

At any rate, I agree that this is low priority at this point.

**Comment by silasmeredith** [comment]
The majority of people will only visit the site once, so if it's working on the first time on Chrome, and working all the time on all other browsers, I think we're fine. I'll label this ticket as "enhancement" to indicate that it is not a blocker for 1.0 release. 

Good investigating!

**Comment by jillh510** [comment]
The issue is much improved with the redirection from http -> https. Most users report no problems.

At least one user reported an issue with Chromium on Linux, a 403 from the Google APIs. That same user saw problems with Chrome and FF.

The Chromium issue may be explained by this page (executive summary: if you're building your own Chromium, getting Google APIs, esp. the location finder) to work is a hassle): http://onefinepub.com/2015/04/fix-chromium-network-location-provider-returning-error-code-403/

**Comment by silasmeredith** [comment]
Okee doke. So are we saying that this bug is "fixed enough" to no longer be a release blocker?

**Comment by jillh510** [comment]
Anyone who builds their own browser from open-source should be able to figure out how to copy-paste a URL. So I think we're good for launch.

**Comment by silasmeredith** [comment]
OK!
