### ISSUE TITLE
Facebook sharing should have some default text

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#80]
"I just sponsored a virtual taco truck. You can, too. Save The Tacos. http://tacotruck.party/#38.867760391067314_-77.18383637677005_13 #ImWithHer #TacoTruckParty"

**Comment by kielni** [comment]
Facebook says no: https://developers.facebook.com/docs/apps/review/prefill
![screen shot 2016-09-12 at 10 16 14 am](https://cloud.githubusercontent.com/assets/1649528/18445340/f716f95c-78d1-11e6-9243-e3cad2ca9054.png)

**Comment by silasmeredith** [comment]
Darn! OK, thank you for checking, @kielni .
