### ISSUE TITLE
What to do if Google Maps API usage limits are exceeded

### ISSUE THREAD

**Issue by jillh510** [DevProgress/more-tacos#83]
The free tier for the Google Maps Javascript API has daily usage limits (25,000 map loads). Post initial launch, we should have a plan for the site if we exceed those limits. Some options:
- An error screen ("Whoops, too many taco trucks today!")
- Use a non-Google API mapping solution. Decause says: "the good news is, is that we have a #peeps-gis team, and the #proj-eventsmap team has done a non-google API maps base they have used before too"

**Comment by jillh510** [comment]
(kielni, parking this one with you for now, to keep an eye on)

**Comment by kielni** [comment]
I don't expect this to be a problem: the daily limit is 25,000 and our 30 day usage is 2,226.
