### ISSUE TITLE
When we're ready for release, clear database of trucks

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#88]

**Comment by kielni** [comment]
I really don't think we should; we want to to look crazy and fun for the very first non-tester person.  They were all individually human placed, so why delete them?

**Comment by silasmeredith** [comment]
I could see it either way. Want to add your comment to the slack channel and see what people think?

**Comment by jillh510** [comment]
I'd assumed we'd ask a bunch of other Dev Progress folks to play around with it before we do any publicity, which should get us initial data. (or maybe I'm overly paranoid that my test trucks, which are sprinkled around randomly, will look silly)

**Comment by silasmeredith** [comment]
True, though they'll probably do the same stuff we did. Except, I suppose, sprinkle trucks in the parks of Eugene, OR.    ;)

**Comment by silasmeredith** [comment]
We also don't have to decide this tonight.

**Comment by kielni** [comment]
I made a copy, then cleared the trucks.
