### ISSUE TITLE
Open new tab when sharing on Facebook

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#89]

**Comment by kielni** [comment]
Its does open a new tab for me on Mac Firefox and Safari; what OS and browser did you see it not open a tab?

**Comment by silasmeredith** [comment]
It's not opening a new tab in:

Chrome on Windows laptop
Safari on iPhone
Chrome on iPhone
Chrome on Chromebook

**Comment by kielni** [comment]
Can you reproduce now?

**Comment by silasmeredith** [comment]
This is working, too! Excellent news.
