### ISSUE TITLE
Open new tab when clicking hyperlinked "warned" in intro paragraph

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#90]

**Comment by silasmeredith** [comment]
Hmmmm, still not opening in a new tab on my broswers (same device/browser list as #89).

Does it take time to propagate to the live site?

**Comment by kielni** [comment]
Do a shift-reload to make sure you're getting the latest; I just tried it and it worked for me.

**Comment by silasmeredith** [comment]
OK, working now!
