### ISSUE TITLE
When dragging truck, the X used to be at the front (left) of the truck. Now it's on top, and it's a bit confusing. Can we move it back to the left?

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#91]

**Comment by silasmeredith** [comment]
This one isn't working for me yet. I tried the same Shift-Reload trick, but no dice. Sorry to keep re-opening tickets; definitely let me know if I'm doing something wrong.

**Comment by kielni** [comment]
this is what I get on tacotruck.party; how does that look?

<img width="335" alt="screen shot 2016-09-12 at 10 13 45 pm" src="https://cloud.githubusercontent.com/assets/1649528/18462343/36d9cd80-7936-11e6-84ff-c543e629018a.png">

**Comment by silasmeredith** [comment]
Perfect, thanks @kielni !
