### ISSUE TITLE
Tweak popup text / buttons

### ISSUE THREAD

**Issue by silasmeredith** [DevProgress/more-tacos#97]
Before saving:
"Your very own (virtual) taco truck! Drag the truck, then..."
[SPONSOR]

After saving:
"I just sponsored a  taco truck at tacotruck.party/"
(automatically opens donation tab)
[FACEBOOK]  [TWITTER]

After redragging:
[SPONSOR]

**Comment by kielni** [comment]
pushed

**Comment by silasmeredith** [comment]
Whoops, mostly done, but one very important part still missing: anytime user hits the [SPONSOR] button, a new tab should open to the HFA donation page. This should happen whether it's the first time the user hits [SPONSOR], or a later time.
